import { State } from './state.js';
import { UI } from './ui.js';
import { Utils } from './utils.js';
import { db, doc, setDoc, getDoc } from './firebase.js';

export const Handlers = {
    // ... (Keep existing importCSV, saveSession, loadSession, refreshAll, editTransaction, saveTransactionEdit, toggleReconcile) ...
    // Note: Copied previously provided methods for context, adding new ones below.
    importCSV: (file) => { /* ... same as before ... */ Papa.parse(file, { header: true, skipEmptyLines: true, complete: (results) => { const newTxs = results.data.map(row => { const dateStr = row['Date'] || row['date'] || row['TransDate']; const desc = row['Description'] || row['Memo'] || row['description'] || 'No Desc'; let amt = parseFloat(row['Amount'] || row['amount'] || row['Grand Total']); if(isNaN(amt)) { const debit = parseFloat(row['Debit']); const credit = parseFloat(row['Credit']); if(!isNaN(debit)) amt = -debit; if(!isNaN(credit)) amt = credit; } if(!dateStr || isNaN(amt)) return null; let category = 'Uncategorized'; for(const rule of State.rules) { if(desc.toLowerCase().includes(rule.keyword.toLowerCase())) { category = rule.category; break; } } return { id: Utils.generateId('tx'), type: 'transaction', date: new Date(dateStr).toISOString().split('T')[0], description: desc, amount: amt, category: category, reconciled: false, job: '' }; }).filter(Boolean); State.data = [...State.data, ...newTxs]; Handlers.refreshAll(); UI.showToast(`Imported ${newTxs.length} transactions`); Handlers.saveSession(); } }); },
    saveSession: async () => { if (State.user) { try { document.getElementById('cloud-status').classList.remove('hidden'); await setDoc(doc(db, 'users', State.user.uid), { data: JSON.stringify(State.data), rules: JSON.stringify(State.rules), categories: JSON.stringify(State.categories), lastUpdated: new Date() }); document.getElementById('cloud-status').classList.add('hidden'); UI.showToast("Saved to Cloud"); } catch (e) { console.error(e); UI.showToast("Save Failed", "error"); } } else { localStorage.setItem('bk_data', JSON.stringify(State.data)); localStorage.setItem('bk_rules', JSON.stringify(State.rules)); localStorage.setItem('bk_cats', JSON.stringify(State.categories)); UI.showToast("Saved Locally"); } },
    loadSession: async () => { if(State.user) { const snap = await getDoc(doc(db, 'users', State.user.uid)); if(snap.exists()) { const d = snap.data(); State.data = JSON.parse(d.data || '[]'); if(d.rules) State.rules = JSON.parse(d.rules); if(d.categories) State.categories = JSON.parse(d.categories); } } else { const local = localStorage.getItem('bk_data'); const rules = localStorage.getItem('bk_rules'); const cats = localStorage.getItem('bk_cats'); if(local) State.data = JSON.parse(local); if(rules) State.rules = JSON.parse(rules); if(cats) State.categories = JSON.parse(cats); } Handlers.refreshAll(); UI.populateRuleCategories(); UI.renderRulesList(); UI.renderCategoryManagementList(); },
    refreshAll: () => { UI.renderDateFilters(); UI.updateDashboard(); if(State.currentView !== 'dashboard') UI.switchTab(State.currentView); },
    editTransaction: (id) => { const tx = State.data.find(d => d.id === id); if(!tx) return; document.getElementById('modal-tx-id').value = id; document.getElementById('modal-category').value = tx.category; document.getElementById('modal-job').value = tx.job || ''; document.getElementById('modal-notes').value = tx.notes || ''; const catList = document.getElementById('category-list'); if(catList) catList.innerHTML = State.categories.map(c => `<option value="${c}">`).join(''); UI.openModal('edit-modal'); },
    saveTransactionEdit: () => { const id = document.getElementById('modal-tx-id').value; const tx = State.data.find(d => d.id === id); if(tx) { tx.category = document.getElementById('modal-category').value; tx.job = document.getElementById('modal-job').value; tx.notes = document.getElementById('modal-notes').value; if(tx.category && !State.categories.includes(tx.category)) State.categories.push(tx.category); UI.closeModal('edit-modal'); Handlers.refreshAll(); Handlers.saveSession(); UI.showToast('Updated'); } },
    toggleReconcile: (id) => { const tx = State.data.find(d => d.id === id); if(tx) { tx.reconciled = !tx.reconciled; Handlers.saveSession(); } },
    
    // --- NEW: Toggle All Reconcile ---
    toggleAllRec: (checked) => {
        // Only toggle VISIBLE transactions (respecting filters/search)
        const visibleTxs = UI.getFilteredData().filter(d => {
            const search = document.getElementById('tx-search').value.toLowerCase();
            return d.type === 'transaction' && (!search || d.description.toLowerCase().includes(search) || d.category.toLowerCase().includes(search));
        });
        
        visibleTxs.forEach(tx => tx.reconciled = checked);
        UI.renderTransactions(); // Re-render to show checks
        Handlers.saveSession();
    },

    // ... (Keep addRule, deleteRule, openApArModal, saveApAr, toggleApArStatus, clearData, exportToIIF, addCategory, deleteCategory) ...
    addRule: () => { const key = document.getElementById('rule-keyword').value.trim(); const cat = document.getElementById('rule-category').value; if(key && cat) { State.rules.push({ keyword: key, category: cat }); UI.renderRulesList(); document.getElementById('rule-keyword').value = ''; Handlers.saveSession(); UI.showToast('Rule Added'); } },
    deleteRule: (index) => { State.rules.splice(index, 1); UI.renderRulesList(); Handlers.saveSession(); },
    addCategory: () => { const name = document.getElementById('new-cat-name').value.trim(); if(name && !State.categories.includes(name)) { State.categories.push(name); State.categories.sort(); UI.populateRuleCategories(); UI.renderCategoryManagementList(); document.getElementById('new-cat-name').value = ''; Handlers.saveSession(); UI.showToast('Category Added'); } },
    deleteCategory: (name) => { if(name === 'Uncategorized') return; State.categories = State.categories.filter(c => c !== name); State.data.forEach(t => { if(t.category === name) t.category = 'Uncategorized'; }); UI.populateRuleCategories(); UI.renderCategoryManagementList(); Handlers.refreshAll(); Handlers.saveSession(); },
    openApArModal: (type) => { document.getElementById('ap-ar-id').value = ''; document.getElementById('ap-ar-type').value = type; document.getElementById('ap-ar-title').textContent = type === 'ar' ? 'Add Invoice' : 'Add Bill'; document.getElementById('ap-ar-party-label').textContent = type === 'ar' ? 'Customer' : 'Vendor'; document.getElementById('ap-ar-date').value = new Date().toISOString().split('T')[0]; document.getElementById('ap-ar-amount').value = ''; document.getElementById('ap-ar-number').value = ''; document.getElementById('ap-ar-party').value = ''; UI.openModal('ap-ar-modal'); },
    saveApAr: () => { const type = document.getElementById('ap-ar-type').value; const item = { id: Utils.generateId(type), type: type, party: document.getElementById('ap-ar-party').value, number: document.getElementById('ap-ar-number').value, date: document.getElementById('ap-ar-date').value, amount: parseFloat(document.getElementById('ap-ar-amount').value) || 0, status: 'unpaid' }; State.data.push(item); UI.closeModal('ap-ar-modal'); Handlers.refreshAll(); Handlers.saveSession(); },
    toggleApArStatus: (id) => { const item = State.data.find(d => d.id === id); if(item) { item.status = item.status === 'unpaid' ? 'paid' : 'unpaid'; Handlers.refreshAll(); Handlers.saveSession(); } },
    clearData: () => { State.data = []; State.rules = []; localStorage.removeItem('bk_data'); localStorage.removeItem('bk_rules'); if(State.user) setDoc(doc(db, 'users', State.user.uid), { data: '[]', rules: '[]' }); UI.closeModal('confirm-modal'); Handlers.refreshAll(); },
    exportToIIF: () => { const bankName = prompt("Bank Account Name:", "Checking"); if(!bankName) return; let iif = `!TRNS\tTRNSID\tTRNSTYPE\tDATE\tACCNT\tNAME\tAMOUNT\tDOCNUM\tMEMO\n!SPL\tSPLID\tTRNSTYPE\tDATE\tACCNT\tNAME\tAMOUNT\tDOCNUM\tMEMO\n!ENDTRNS\n`; State.data.filter(d => d.type === 'transaction').forEach(tx => { const date = new Date(tx.date).toLocaleDateString('en-US', {month: '2-digit', day: '2-digit', year: 'numeric'}); const type = tx.amount < 0 ? 'EXPENSE' : 'DEPOSIT'; iif += `TRNS\t\t${type}\t${date}\t${bankName}\t\t${tx.amount.toFixed(2)}\t\t${(tx.description+' '+tx.job).trim()}\n`; iif += `SPL\t\t${type}\t${date}\t${tx.category}\t\t${(-tx.amount).toFixed(2)}\t\t${(tx.description+' '+tx.job).trim()}\n`; iif += `ENDTRNS\n`; }); const blob = new Blob([iif], { type: 'text/plain' }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = 'quickbooks.iif'; a.click(); }
};
